"""Document IR -- the semantic tree at the centre of Caissa Studio (SPEC 5).

Every importer produces one of these; every exporter consumes one. That is
ADR-0002 in one sentence, and it is what turns N x M format converters into
N + M, makes "change the notation language of the whole book" a single edit, and
makes round-trip fidelity something that can be *measured* rather than hoped for.

The tree is immutable per version, addressable by stable
:class:`~caissa.core.model.ids.ULID`, and serialisable to JSON with an explicit
schema version and a migration chain. It depends on nothing but the standard
library -- no Qt, no PyMuPDF, no ``python-chess`` -- so it loads in milliseconds
and can be exercised anywhere.

Layout
------

``ids``, ``registry``, ``base``, ``provenance``, ``reflect``
    Foundations: identity, the tag registry, the node base, where a node came
    from, and cached type introspection.
``props``, ``marks``, ``styles``
    Formatting: the complete SPEC 5.2 run and paragraph property model, board
    annotations, and the named-style cascade.
``inline``, ``blocks``, ``diagram``, ``game``, ``document``
    The node vocabulary itself.
``serialize``, ``migrations``
    Lossless JSON with a versioned envelope and an upgrade chain.
``visitor``, ``validate``, ``diff``, ``degradation``
    The tools built on the tree: traversal and rewriting, structural
    validation, semantic comparison, and the exporter's loss ledger.
"""

from __future__ import annotations

from caissa.core.model.base import (
    IRNode,
    IRTypeError,
    class_for_tag,
    ir_node,
    is_ir_dataclass,
    iter_registered,
    tag_for_class,
    tag_of,
)
from caissa.core.model.blocks import (
    Block,
    Callout,
    CalloutKind,
    CodeBlock,
    ColumnLayout,
    Endnote,
    Figure,
    FigurePlacement,
    Footnote,
    Group,
    GroupRole,
    Heading,
    ImageBlock,
    ListBlock,
    ListItem,
    ListKind,
    ListMarkerStyle,
    MathBlock,
    PageBreak,
    PageGeometry,
    Paragraph,
    Quote,
    RawPassthrough,
    SectionBreak,
    SectionBreakKind,
    Table,
    TableCell,
    TableColumn,
    TableOfContents,
    TableRow,
    ThematicBreak,
    VerticalCellAlignment,
    block_children,
)
from caissa.core.model.degradation import (
    DegradationKind,
    DegradationRecorder,
    DegradationReport,
    DegradationWarning,
)
from caissa.core.model.diagram import (
    SQUARE_COUNT,
    BoardTheme,
    CaptionPosition,
    CoordinateStyle,
    Diagram,
    DiagramSource,
    DiagramStyle,
    FenCandidate,
    PiecePlacementStyle,
    RecognitionPath,
    RecognitionResult,
    SquareRepair,
)
from caissa.core.model.diff import (
    ChangeKind,
    DiffEntry,
    DiffReport,
    MatchStrategy,
    semantic_diff,
)
from caissa.core.model.document import (
    Contributor,
    ContributorRole,
    Document,
    DocumentMetadata,
    DocumentSettings,
    MetadataEntry,
    Resource,
    ResourceKind,
)
from caissa.core.model.game import (
    SEVEN_TAG_ROSTER,
    ClockAnnotation,
    ClockKind,
    EvalAnnotation,
    EvalKind,
    GameHeaders,
    GameRenderOptions,
    GameScore,
    MoveNode,
    PgnTag,
    VariationStyle,
)
from caissa.core.model.ids import ULID, ULIDError, new_ulid
from caissa.core.model.inline import (
    INLINE_WRAPPERS,
    Anchor,
    Emphasis,
    ImageInline,
    IndexEntry,
    Inline,
    InlineDiagram,
    LineBreak,
    Link,
    LinkKind,
    MathInline,
    Move,
    NagSymbol,
    NonBreakingSpace,
    NoteRef,
    Orientation,
    PieceGlyph,
    RawInline,
    SmallCaps,
    Space,
    SpaceKind,
    Span,
    Strike,
    Strong,
    Subscript,
    Superscript,
    Tab,
    Text,
    Underline,
    inline_children,
    plain_text,
)
from caissa.core.model.marks import Mark, MarkKind, MarkLineStyle, arrow, circle, highlight
from caissa.core.model.migrations import (
    CURRENT_SCHEMA_VERSION,
    DEFAULT_REGISTRY,
    JsonObject,
    JsonValue,
    Migration,
    MigrationError,
    MigrationRegistry,
)
from caissa.core.model.props import (
    EMPTY_PARAGRAPH_PROPS,
    EMPTY_RUN_PROPS,
    Alignment,
    Border,
    Borders,
    BorderStyle,
    Color,
    ColorSpace,
    EmphasisMark,
    FontFeature,
    FontStretch,
    FontWeight,
    LengthUnit,
    LigatureMode,
    LineSpacing,
    LineSpacingRule,
    ListMarkerAlignment,
    Measure,
    NumberingRef,
    NumeralFigure,
    NumeralSpacing,
    Padding,
    ParagraphProps,
    RunProps,
    SmallCapsMode,
    StrikeStyle,
    TabAlignment,
    TabLeader,
    TabStop,
    TextDirection,
    TextOutline,
    TextShadow,
    TextTransform,
    UnderlineStyle,
    VariationAxis,
    VerticalAlign,
)
from caissa.core.model.provenance import ConfidenceBand, Provenance, Rect, SourceKind
from caissa.core.model.serialize import (
    SerializationError,
    document_from_payload,
    document_to_payload,
    dumps,
    loads,
    node_from_payload,
    node_to_payload,
)
from caissa.core.model.styles import (
    CharacterStyle,
    DiagramStyleDef,
    ListStyle,
    ListStyleLevel,
    ParagraphStyle,
    ResolvedProps,
    StyleError,
    StyleSheet,
    TableStyle,
    resolve_paragraph_props,
    resolve_run_props,
    style_chain,
)
from caissa.core.model.validate import Severity, ValidationIssue, validate
from caissa.core.model.visitor import (
    NodePath,
    PathStep,
    Transformer,
    TransformError,
    Visitor,
    find,
    walk,
)

__all__ = [
    "CURRENT_SCHEMA_VERSION",
    "DEFAULT_REGISTRY",
    "EMPTY_PARAGRAPH_PROPS",
    "EMPTY_RUN_PROPS",
    "INLINE_WRAPPERS",
    "SEVEN_TAG_ROSTER",
    "SQUARE_COUNT",
    "ULID",
    "Alignment",
    "Anchor",
    "Block",
    "BoardTheme",
    "Border",
    "BorderStyle",
    "Borders",
    "Callout",
    "CalloutKind",
    "CaptionPosition",
    "ChangeKind",
    "CharacterStyle",
    "ClockAnnotation",
    "ClockKind",
    "CodeBlock",
    "Color",
    "ColorSpace",
    "ColumnLayout",
    "ConfidenceBand",
    "Contributor",
    "ContributorRole",
    "CoordinateStyle",
    "CoordinateStyle",
    "DegradationKind",
    "DegradationRecorder",
    "DegradationReport",
    "DegradationWarning",
    "Diagram",
    "DiagramSource",
    "DiagramStyle",
    "DiagramStyleDef",
    "DiffEntry",
    "DiffReport",
    "Document",
    "DocumentMetadata",
    "DocumentSettings",
    "Emphasis",
    "EmphasisMark",
    "Endnote",
    "EvalAnnotation",
    "EvalKind",
    "FenCandidate",
    "Figure",
    "FigurePlacement",
    "FontFeature",
    "FontStretch",
    "FontWeight",
    "Footnote",
    "GameHeaders",
    "GameRenderOptions",
    "GameScore",
    "Group",
    "GroupRole",
    "Heading",
    "IRNode",
    "IRTypeError",
    "ImageBlock",
    "ImageInline",
    "IndexEntry",
    "Inline",
    "InlineDiagram",
    "JsonObject",
    "JsonValue",
    "LengthUnit",
    "LigatureMode",
    "LineBreak",
    "LineSpacing",
    "LineSpacingRule",
    "Link",
    "LinkKind",
    "ListBlock",
    "ListItem",
    "ListKind",
    "ListMarkerAlignment",
    "ListMarkerStyle",
    "ListStyle",
    "ListStyleLevel",
    "Mark",
    "MarkKind",
    "MarkLineStyle",
    "MatchStrategy",
    "MathBlock",
    "MathInline",
    "Measure",
    "MetadataEntry",
    "Migration",
    "MigrationError",
    "MigrationRegistry",
    "Move",
    "MoveNode",
    "NagSymbol",
    "NodePath",
    "NonBreakingSpace",
    "NoteRef",
    "NumberingRef",
    "NumeralFigure",
    "NumeralSpacing",
    "Orientation",
    "Padding",
    "PageBreak",
    "PageGeometry",
    "Paragraph",
    "ParagraphProps",
    "ParagraphStyle",
    "PathStep",
    "PgnTag",
    "PieceGlyph",
    "PiecePlacementStyle",
    "Provenance",
    "Quote",
    "RawInline",
    "RawPassthrough",
    "RecognitionPath",
    "RecognitionResult",
    "Rect",
    "ResolvedProps",
    "Resource",
    "ResourceKind",
    "RunProps",
    "SectionBreak",
    "SectionBreakKind",
    "SerializationError",
    "Severity",
    "SmallCaps",
    "SmallCapsMode",
    "SourceKind",
    "Space",
    "SpaceKind",
    "Span",
    "SquareRepair",
    "Strike",
    "StrikeStyle",
    "Strong",
    "StyleError",
    "StyleSheet",
    "Subscript",
    "Superscript",
    "Tab",
    "TabAlignment",
    "TabLeader",
    "TabStop",
    "Table",
    "TableCell",
    "TableColumn",
    "TableOfContents",
    "TableRow",
    "TableStyle",
    "Text",
    "TextDirection",
    "TextOutline",
    "TextShadow",
    "TextTransform",
    "ThematicBreak",
    "TransformError",
    "Transformer",
    "ULIDError",
    "Underline",
    "UnderlineStyle",
    "ValidationIssue",
    "VariationAxis",
    "VariationStyle",
    "VerticalAlign",
    "VerticalCellAlignment",
    "Visitor",
    "arrow",
    "block_children",
    "circle",
    "class_for_tag",
    "document_from_payload",
    "document_to_payload",
    "dumps",
    "find",
    "highlight",
    "inline_children",
    "ir_node",
    "is_ir_dataclass",
    "iter_registered",
    "loads",
    "new_ulid",
    "node_from_payload",
    "node_to_payload",
    "plain_text",
    "resolve_paragraph_props",
    "resolve_run_props",
    "semantic_diff",
    "style_chain",
    "tag_for_class",
    "tag_of",
    "validate",
    "walk",
]
